const a=3
const b=7
const result= a & b
console.log(result)

/*  HERE WE USED BITWISE AND OPERATOR IT WILL WORK LIKE IF A=3 THAT MEAN 11 ITS BINARY CONVERSION AND B=7 ITS BINARY CONVERSION IS 111
IF WE WIILL USE A & B THAT MEANS IT WILL CHECK 111 AND 11 AND GIVE OUTPUT 11 MEAN 3. FIRST 1 WILL GIVE OUT PUT */


const c=4
const d=5
console.log(c ^ d) 